---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - gemfiles/**/*

Naming/FileName:
  Exclude:
    - lib/i18n-js.rb
    - lib/guard/i18n-js.rb

Style/PerlBackrefs:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/AttributeAssignment:
  Enabled: false
