// File generated by i18n-js on 2022-12-10 15:37:00 +0000

import { i18n } from "config/i18n";

i18n.store({
  "en": {
    "bunny_rabbit_adventure": "bunny rabbit adventure",
    "hello_sunshine": "hello sunshine!",
    "time_for_bed": "time for bed!"
  },
  "es": {
    "bunny_rabbit_adventure": "conejito conejo aventura",
    "bye": "adios",
    "time_for_bed": "¡hora de acostarse!"
  },
  "pt": {
    "bunny_rabbit_adventure": "a aventura da coelhinha",
    "bye": "tchau",
    "time_for_bed": "hora de dormir!"
  }
});
