// File generated by i18n-js on 2022-12-10 15:37:00 +0000

import { i18n } from "config/i18n";

i18n.store({
  "en": {
    "bunny rabbit adventure": "bunny rabbit adventure",
    "hello sunshine!": "hello sunshine!",
    "time for bed!": "time for bed!"
  },
  "es": {
    "bunny rabbit adventure": "conejito conejo aventura",
    "bye": "adios",
    "time for bed!": "hora de acostarse!"
  },
  "pt": {
    "bunny rabbit adventure": "a aventura da coelhinha",
    "bye": "tchau",
    "time for bed!": "hora de dormir!"
  }
});
